# ITMAL Exercise

REVISIONS|
---------|-----------
2018-1218|CEF, initial.                  
2019-0131|CEF, spell checked and update. 
2019-0131|CEF, updated Pearson's r to work with random vars. instead of matrices.
2019-0131|CEF, updated mean-var fun and biased/un-biased var estimator update.
2019-0204|CEF, minor Pearsons's r update.
2019-0204|CEF, changed headline.
2019-0204|CEF, added bias comment in cross- auto-covariance.
2019-0204|CEF, changed eqs for cross- auto-covariance.
2019-0205|CEF, spell checked. 

## Statistics

### Mean and Variance

The mean and variance (and hence the standard deviation) for a random variable $X$ can for a population of $N$ samples be estimated as

$$
    \newcommand\rem[1]{}
    \rem{ITMAL: CEF def and LaTeX commands, rember: no newlines in defs}
    \newcommand\eq[2]{#1 &=& #2\\}
    \newcommand\ar[2]{\begin{array}{#1}#2\end{array}}
    \newcommand\ac[2]{\left[\ar{#1}{#2}\right]}
    \newcommand\st[1]{_{\mbox{\scriptsize #1}}}
    \newcommand\norm[1]{{\cal L}_{#1}}
    \newcommand\obs[2]{#1_{\mbox{\scriptsize obs}}^{\left(#2\right)}}
    \newcommand\diff[1]{\mbox{d}#1}
    \newcommand\pown[1]{^{(#1)}}
    \def\pownn{\pown{n}}
    \def\powni{\pown{i}}
    \def\powtest{\pown{\mbox{\scriptsize test}}}
    \def\powtrain{\pown{\mbox{\scriptsize train}}}
    \def\bX{\mathbf{X}}
    \def\bZ{\mathbf{Z}}
    \def\bx{\mathbf{x}}
    \def\bw{\mathbf{w}}
    \def\by{\mathbf{y}}
    \def\bz{\mathbf{z}}
    \def\btheta{{\boldsymbol\theta}}
    \def\half{\frac{1}{2}}
    \begin{array}{rl}
        E[X] &= \frac{1}{N} \sum_{i=1}^N X_i\\
             &= \mu_X\\
        V[X] &= E[(X_i -E[X])(X_i -E[X])] \\
             &= E[X_i X_i] - E[X]^2\\
             &= \left( \frac{1}{N} \sum_{i=1}^N X_i X_i \right) - \mu_X^2\\
             &= \sigma_X^2\\
        \sigma & = \sqrt{V}
    \end{array}
$$

Notice that the $1/N$ factor most often appears as $1/(N-1)$ for the variance estimation. 

When using the factor $1/(N-1)$, $\hat V$ is said to be the best unbiased estimator, when it is $1/N$ it will be biased, both assuming an underlying normal distribution. 

Be very careful when rewriting the biased equation above to the unbiased variance estimator. Anyway, for large $N$ this factor has less effect.

#### Qa Create a mean and variance function for some input data

Your python function should be named ```MeanAndVariance()```, it takes a vector as input parameter, and returns TWO parameters, namely mean and variance. 

Python allows for return of zero, one, or more parameters from a function, without having to place, say two output parameters in a tuple, like in C++ ```return make_pair<float,float>(mean, variance)```.

Test it via the ```y``` input and test-vectors below, go for the biased variance estimator at first.

Then extend it to handle both biased and un-biased estimators, create your own test case.

In [357]:
import numpy as np
# TODO: Qa...

def MeanAndVariance(x): 
    # Your impl here
    N_biased = x.size
    N_unbiased = x.size - 1
    mean = 1/x.size*sum(x)    
    variance_biased = 1/N_biased*sum((x - mean)**2)
    variance_unbiased = 1/N_unbiased*sum((x - mean)**2)    
    return mean, variance_biased, variance_unbiased

# TEST vectors: mean and variance calc
y = np.array([1,2,3,4])
m, v_biased, v_unbiased = MeanAndVariance(y)

expected_m = 2.5  
expected_v_biased = 1.25 # factor 1/n
expected_v_unbiased = 1.6666666666666667 # factor 1/(n-1)

print("m=",m,", diff=", m-expected_m)
print("v_biased=",v_biased,", diff=", v_biased-expected_v_biased)
print("v_unbiased=",v_unbiased,", diff=", v_unbiased-expected_v_unbiased)
print(v_biased,np.mean(y), np.var(y)) # np.var is biased(n)

m= 2.5 , diff= 0.0
v_biased= 1.25 , diff= 0.0
v_unbiased= 1.6666666666666665 , diff= -2.220446049250313e-16
1.25 2.5 1.25


##### Auto- and Cross-covariance in Matrix Notation

Now let's goto full matrix notation for the covariance. For a data matrix $\bX$  

$$
    \bX = \ac{cccc}{
        x_1^{(1)} & x_2^{(1)} & \cdots & x_d^{(1)} \\
        x_1^{(2)} & x_2^{(2)} & \cdots & x_d^{(2)}\\
        \vdots \\
        x_1^{(n)} & x_2^{(n)} & \cdots & x_d^{(n)}\\
    }
$$

the previous one-dimensional random variable $X$ can now be seen as a $d$-dimensional vector $\bx\powni$, that is one of the data rows in the full data matrix

$$
    X_i \to \bx\powni = \left[  x_1\powni~~ x_2\powni~~ \cdots~~ x_d\powni\right]^T
$$

The (biased) auto–covariance matrix can be estimated as

$$
  \ar{rl}{
            E[\bX] &= \mu_\bX \\
                   &= \frac{1}{n} \sum_{i=1}^{n} \bx\powni \\ \\
       \Sigma(\bX) &= \mbox{cov}(\bX,\bX) \\
                   &= \frac{1}{n} \sum_{i=1}^{n} \bx\powni\bx^{(i)T} - \mu_\bX\mu_\bX^T 
   }
   \rem{
     \ar{ll}{
        \Sigma(\bX) &= \mbox{cov}(\bX,\bX)\\
          &= E\left[(\bX-\mu_\bX)(\bX-\mu_\bX)^T \right]\\
          &= E\left[ \bX\bX^T \right] - E[\bX]E[\bX]^T\\
          &= E\left[ \bX\bX^T \right] - \mu_\bX\mu_\bX^T
      }
   }
$$

with implicit $1/N$ factor here (inside the first $E[\cdot]$), so the definition is a biased covariance. You may opt to use the factor $1/(N-1)$ instead.

For yet another data matrix $\bZ $ the (biased) cross-covariance matrix is given by

$$
  \ar{ll}{
       \Sigma(\bX,\bZ) &= \mbox{cov}(\bX,\bZ)\\
            &= \frac{1}{n} \sum_{i=1}^{n} \bx\powni\bz^{(i)T} - \mu_\bX\mu_\bZ^T 
        \rem{
            &= E\left[(\bX-\mu_\bX)(\bZ-\mu_\bZ)^T \right]\\
            &= E\left[ \bX\bZ^T \right] - E[\bX]E[\bZ]^T\\
            &= E\left[ \bX\bZ^T \right] - \mu_\bX\mu_\bZ^T
        }
   }
$$
(NOTE: equation to-be confirmed)

#### Qb Create a function that generates the auto-covariance matrix $\Sigma(\bX)$.

Create the function from scratch or find some suitable implementation on the net. 

Direct use of `numpy.cov` (or other libs) not permitted, though it could serve as a test-stub.  Be very careful regarding the normalization factor when comparing with numpy's or matlabs covar functions. If you are going to use `numpy.cov` for cross-testing, be sure to read up on its `rowvar` parameter!  

Make some suitable test data, perhaps share a test-stub with another ITMAL group.

Explain the elements in the $\Sigma$ matrix, what are the diagonal elements $\Sigma_{ii}$, and what does off-diagonal elements, $\Sigma_{ij}$ for $i \neq j$ represent?


In [36]:
# Covariance
def cov(x, y):
    xbar, ybar = x.mean(), y.mean()
    return np.sum((x - xbar)*(y - ybar))/(len(x) - 1)

# Covariance matrix
def cov_mat(X):
    return np.array([[cov(X[0], X[0]), cov(X[0], X[1])], \
                     [cov(X[1], X[0]), cov(X[1], X[1])]])

# Calculate covariance matrix 
cov_mat(X.T) # (or with np.cov(X.T))

array([[1.17583333, 0.15833333],
       [0.15833333, 0.25      ]])

In [220]:
# TODO: Qb...
import numpy as np

def AutoCovariance(X):
    X_transposed = np.transpose(X)
    size = X.shape[0]
    trans_mean = np.mean(X_transposed, axis = 1)
    x_mean = np.mean(X, axis = 0)
    sumOfVectors = 0
    # Iterate through and pull out each vector separately
    for i in range(0, size):
        # Pulls out vectors: rows in transposed X and columns in X 
        trans_vec = X_transposed[:,i]
        x_vec = X[i,:]
        
        # Calculates the difference to the mean values
        trans_vec_diff = trans_vec - trans_mean
        x_vec_deff = x_vec - x_mean
        
        # Adds the product of the vectors to the sumOfVectors variable
        sumOfVectors += np.outer(trans_vec_diff, x_vec_deff)
    
    return 1/size*(sumOfVectors)
    
    #X_mean = np.mean(X, axis=0) 
    #transposed_mean = np.mean(X_transposed, axis = 0)
    #print((1/size*np.dot(X_transposed,X) - trans_mean*X_mean))
    
      
# 2 observations, 3 variables. Observed values are held in the 3 columns of the array X   
X = np.array([[0.1,2, 0.2], [0.2,1, 0.1], [0.2,1, 4], [-2,1, 0.1]])
X_transposed = X.transpose

autocov = AutoCovariance(X)

# Covariance is a 3x3 array of values. Diagonal elements are the variances in the variables x_i
cov = np.cov(X, rowvar=False, bias=True)
print()
print("cov=",cov,", diff=", autocov-cov)


cov= [[ 0.881875  0.11875   0.5725  ]
 [ 0.11875   0.1875   -0.225   ]
 [ 0.5725   -0.225     2.805   ]] , diff= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Pearson's r

Now, let us step back again from matrix-vectors to the random variables, $X$ and $Y$. The standard correlation, or Pearson's r, is given by the 'normalized' cross-correlation between the random variables, $X$ and $Y$

$$
    \mbox{Pearson's r} = \rho(X,Y) = \frac{cov(X,Y)}{\sigma(X)\sigma(Y)}
$$

The (dimensionless) Pearson's r is used in [HOML] and is somewhat similar to the (also dimensionless) $R^2$ score we used last time. 

Let's try to implement the Pearsons's r now...

#### Qc Create a Pearson's r function

Again, create some test data, and implement your own function or get inspiration by searching the net for code.

You need a full implementation, again not use of libs; so direct use of `numpy.corrcoef` not permitted. But it will serve as a good test function...

Write a short description of Pearson's r, giving is range (possible min/max values) and a description of what they mean, and classify it as being a loss/scoring function. 

Hint: look at these links for the Pearson's r...you can find both algorithm details
as well as test data here

https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html
http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html


OPTIONAL: try to re-create some of the data for the plots in figure 2-14 [HOML], and run your Pearson's r function on the test data. 

In [ ]:
# TODO: Qc...