In [8]:
import numpy as np
from keras.utils.np_utils import to_categorical

y = np.array([1, 2, 0, 4, -1])
y_cat = to_categorical(y)

print(y_cat)

# prints 
#[[0. 1. 0. 0. 0.]  => i=0, class 1
# [0. 0. 1. 0. 0.]  => i=1, class 2
# [1. 0. 0. 0. 0.]  => i=2, class 0
# [0. 0. 0. 0. 1.]  => i=3, class 4
# [0. 0. 0. 0. 1.]] => i=4, also class 4!
#                      NOTE: no class 3

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
