# Preprocessing of Data

## Standardization

### First standarization...

In [30]:
import numpy as np

from sklearn.preprocessing import scale, StandardScaler
from libitmal import utils as libmalutils

# Some dummy data...
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])
y_train = np.array([1, 0, 1])

X_scaled = scale(X_train)

libmalutils.PrintMatrix(X_scaled,'X_scaled=')
print()
print(f'X_scaled.mean()={X_scaled.mean():0.3f}')
print(f'X_scaled.std() ={X_scaled.std():0.3f}')
print('\nColumn-wise mean and std:\n')
print(f'X_scaled.mean()={X_scaled.mean(axis=0)}')
print(f'X_scaled.std() ={X_scaled.std (axis=0)}')

X_scaled=[[ 0.   -1.22  1.34]
          [ 1.22  0.   -0.27]
          [-1.22  1.22 -1.07]]

X_scaled.mean()=0.000
X_scaled.std() =1.000

Column-wise mean and std:

X_scaled.mean()=[0. 0. 0.]
X_scaled.std() =[1. 1. 1.]


### Now via a preprocess (fit-predict interface) scaler..

In [23]:
# scaler = StandardScaler().fit(X_train)
print(scaler)
print()
print(f'scaler.mean_ ={scaler.mean_}')                                      
print(f'scaler.scale_={scaler.scale_}')        
print(f'scaler.var_  ={scaler.var_}')          
print()                           

libmalutils.PrintMatrix(scaler.transform(X_train),'scaler.transform(X_train)=') 
libmalutils.PrintMatrix(scaler.transform(X_train).std(axis=0),'scaler.transform(X_train)=') 

StandardScaler(copy=True, with_mean=True, with_std=True)

scaler.mean_ =[1.         0.         0.33333333]
scaler.scale_=[0.81649658 0.81649658 1.24721913]
scaler.var_  =[0.66666667 0.66666667 1.55555556]

scaler.transform(X_train)=[[ 0.   -1.22  1.34]
                           [ 1.22  0.   -0.27]
                           [-1.22  1.22 -1.07]]
scaler.transform(X_train)=[1. 1. 1.]


### And finally via a Pipeline

In [32]:
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import make_pipeline

mypipeline = make_pipeline(
    StandardScaler(), 
    GaussianNB(priors=None)
)

mypipeline.fit(X_train, y_train)
print(mypipeline.predict(X_train)) # just a dummy demo, predict on train data

[1 0 1]
